url: "https://agilesnowball.com"
baseurl: ""
title: "Agile Snowball"

author: "Richard Thombs"
email: "richard@gearstone.uk"
github_username: "richardthombs"
twitter_username: "stonyuk"
description: "Lessons learned and challenges faced in trying to keep an ASP.NET and SQL Server web application agile enough to take advantage of the latest tools, technologies and methodologies."

permalink: /:year/:title:output_ext

plugins:
  - jekyll-postcss
#  - jekyll-feed
